# -*- coding: utf-8 -*-
"""airmap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F4_E5rn9ukWjj_glsrOYIXxCpQmrvKcc
"""

import pandas as pd
import folium
from folium import plugins
import json
from bson.objectid import ObjectId
from time import strftime
from datetime import datetime, timedelta
import urllib.request
import time
import requests

#https://pm25.lass-net.org/AirBox/newtaipei18.json
#https://pm25.lass-net.org/AirBox/taichung19.json
#https://pm25.lass-net.org/AirBox/kaohsiung18.json
#https://pm25.lass-net.org/AirBox/taoyuan19.json
r = requests.get("https://pm25.lass-net.org/AirBox/taichung19.json", verify=False)
a=json.loads(r.text)

myMap = folium.Map([24.1393624, 120.6782234], zoom_start=10)
for i in range(len(a['feeds'])):
  label=a['feeds'][i]
  if label['gps_lon']!='N/A':
    lon=float('{:.3f}'.format(label['gps_lon']))
  else:
    lon=0
  if label['gps_lat']!='N/A':
    lat=float('{:.3f}'.format(label['gps_lat']))
  else:
    lat=0
  if label['pm25']<=35:
    indexc='green'
  elif 35<label['pm25']<=53:
    indexc='orange'
  elif 53<label['pm25']<=70:
    indexc='red'
  else:
    indexc='purple'
  location=label['site']+'\n PM2.5:'+str(label['pm25'])+'\n 溫度:'+str(label['temperature'])+'\n 濕度:'+str(label['humidity'])
  myMap.add_child(folium.Marker(location=[lat, lon],popup=location,icon=folium.Icon(icon='10',color=indexc)))
  #myMap.add_child(plugins.MarkerCluster([lat, lon],name=bb))
myMap